extends Spatial

var marker_info = {
	"marker_a1_door": {
		"method": "open_door",
		"door": "a1",
	},
	"marker_a2_door": {
		"method": "open_door",
		"door": "a1",
	}
}

func _ready():
	doors.register_door(self, "a1", get_parent(), Vector3.UP, 0, -PI/2.0, 2.0)
	markers.init_markers(self, marker_info)
func _physics_process(delta):
	pass
func _process(delta):
	pass

func open_door(data):
	var door = data.door
	if doors.get_state(self, door) == 0:
		doors.open_door(self, door)
	elif doors.get_state(self, door) == 1:
		doors.close_door(self, door)
